### ISSUE TITLE
VCV 1.0 updates comin?

### ISSUE THREAD

**Issue by smok-e** [wlaub/vcv#7]
will you update  the modules for V1.0?

**Comment by wlaub** [comment]
Oops. This is already done, but it looks like I never updated the releases in the repo. Latest windows build of 1.0 should be available in the master branch now.

**Comment by smok-e** [comment]
great, could you post a compiled win version?

**Comment by wlaub** [comment]
Welp, that's three people with this issue now. I will look into it this weekend.

**Comment by wlaub** [comment]
I'm going to focus on tracking this issue in https://github.com/wlaub/vcv/issues/6, since that was the first report. It looks like the issue is related to Pleaides, which probably does some objectively wrong things from a software engineering POV. There's a build there that removes Pleiades and seems to work on the computer I was able to reproduce the issue on.

**Comment by wlaub** [comment]
Closing this as 1.0 updates have since been done, and the crashing issue is tracked elsewhere.
